---
# tasks file for ait.phusion.thunderbird

- name: Install thunderbird
  apt:
    name: thunderbird

- name: Add custom syspref.js to activate auto config
  copy:
    src:  syspref.js
    dest: /etc/thunderbird/syspref.js
    mode: 0644

- name: Add custom thunderbird.cfg containing auto config
  copy:
    src:  thunderbird.cfg
    dest: /usr/lib/thunderbird/thunderbird.cfg
    mode: 0644

  
